name:                icfpc2024
version:             0.1.0.0
github:              "icfpc-dniwe/icfpc2024"
license:             BSD-3-Clause
author:              "DNIWE :: a"

dependencies:
- base >= 4.7 && < 5
- bytestring >= 0.11
- megaparsec >= 9.5
- mtl >= 2.3
- unordered-containers >= 0.2.19
- monad-st >= 0.2
- text >= 2.0
- interpolatedstring-perl6 >= 1.0.0
- process >= 1.6

ghc-options:
- -Wall
- -O2

default-extensions:
- OverloadedStrings
- FlexibleContexts
- ConstraintKinds
- TypeOperators
- LambdaCase
- RankNTypes
- RecordWildCards
- GeneralizedNewtypeDeriving
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- QuasiQuotes
- BangPatterns

library:
  source-dirs: src

executables:
  interpreter:
    main: Interpreter.hs
    source-dirs: app
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2024

  string-encoder:
    main: StringEncoder.hs
    source-dirs: app
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2024

  sender:
    main: Sender.hs
    source-dirs: app
    other-modules: []
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - icfpc2024
    - dotenv >= 0.11.0.0
    - http-client >= 0.7
    - wreq >= 0.5.4.0
    - lens >= 4.5

tests:
  test-suite:
    main: Main.hs
    source-dirs: test
    dependencies:
      - icfpc2024
      - HTF >= 0.15
